---
title: "Mating events at increasing distance"
author: "Tom Ellis"
date: "3/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
library(tidyverse)

source("002.library/R/mating_events.R")
```

```{python}
# Python code to import the population data and a table of mating events,
# and merge distances with flower colour data

import numpy as np
import pandas as pd

# FAPS objects and distance matrices are generated in a separate script.
exec(open('003.scripts/setup_FAPS_GPS.py').read())
# Make the matrix of distances into a dataframe
am_data.distance_df = pd.DataFrame({
    'mother'   : np.repeat(list(am_data.mothers), am_data.n_candidates),
    'father'   : np.tile(am_data.candidates, len(am_data.mothers)),
    'distance' : am_data.distances.flatten()
})
# Merge with flower colours
am_data.distance_df = am_data.distance_df.\
merge(am_data.flower_colours, how = 'left', left_on = "father", right_index = True)

# Data file containing information about mating events.
# For each MCMC iteration this gives combinations of mother and father, plus a 
# posterior inclusion probability that the mating event happened.
sires = pd.read_csv(
  "005.results/011_fitness_all_genotypes/004_mcmc_restrict_kurtosis/sires.csv"
  )
sires.rename( columns={'Unnamed: 0':'iter', 'Unnamed: 1':'mating_event'}, inplace=True ) # rename index columns

# Merge with flower colour data
# sires = sires.merge(am_data.flower_colours, how = 'left', left_on = "father", right_index = True)
# Merge with distances
sires = sires.merge(am_data.distance_df, how = 'left', on = ["mother", "father"])
# Remove candidates with no distance info
sires = sires.loc[~sires['distance'].isnull()].reset_index()

```

```{r convert-data-from-python}
# Vector of plant names for which flower colour phentoype is known
this_colour <- py$am_data$flower_colours %>% 
  filter(simple_colour != "unkown") %>%
  row.names()

# Bring the table of mating events over from the python environment, and tidy it up
sires  <- as.data.frame(py$sires)
sires <- sires %>%
  filter(
    # simple_colour %in% c("FR", "hybrid", "Ye"),
    mother %in% this_colour # subset mothers with known flower colours
  ) %>% 
  mutate(
    simple_colour = as.factor(simple_colour),
    # Reticulate does something funny to `rosea` and `sulfurea`, so they need to be converted back to vectors
    rosea = as.factor(unlist(sires$rosea)),
    sulfurea = as.factor(unlist(sires$sulfurea))
  )

# Bring the table of distances over from Python, and tidy it up
distance_df <- py$am_data$distance_df
distance_df <- distance_df %>% 
  mutate(
    # Reticulate does something funny to `rosea` and `sulfurea`, so they need to be converted back to vectors
    rosea = as.factor(unlist(distance_df$rosea)),
    sulfurea = as.factor(unlist(distance_df$sulfurea))
  ) %>%   
  filter(
    !is.na(distance),
    distance <= 2000,
    mother != father,
    mother %in% this_colour
  )

# Add a column diving mating events up into distances classes (demes) based on
# how far the father is from the mother
bins <-c(0, 2.3, 5.8, 9.5, 17.5, 30, 51, 90, 154, 303, 2000)
sires$bins <- cut(sires$distance, bins)
distance_df$bins <- cut(distance_df$distance, bins)

# A formal assessment of quantiles 
sires %>% 
  group_by(iter) %>% 
  summarise(
    quantile = seq(0.1, 1, 0.1),
    distance = quantile(distance, seq(0.1, 1, 0.1))
  ) %>% 
  group_by(quantile) %>% 
  summarise(
    distance = mean(distance)
  )


```

```{r calculate-mating-events-all-mothers, eval=F}
#' Calculate observed and expected mating events in each deme for all mothers.
#' Notice that this is flagged as `eval=FALSE` so that this does not need to be
#' done every you knit this document; the next chunk imports the output from disk 

set.seed(6)

iter <- unique(sires$iter) # Index MCMC iteration; it starts from 0 because Python
mating_events_all_mothers <- vector('list', length(iter)) # Empty list to store results for each iteration

# Initializes the progress bar
pb <- txtProgressBar(min = 0, max = max(iter), style = 3)

# Loop over iterations and count mating events for each
for(i in iter){
  setTxtProgressBar(pb, i)
  
  these_sires <- sires %>%
    filter(iter == i)
  
  # Add a weight to the data frame of distances to all males reflecting how many
  # mating events came from each mother.
  w <- these_sires %>% 
    group_by(mother) %>% 
    summarise(
      prob = sum(prob)
    ) %>% 
    mutate(
      prob = prob / max(prob)
    ) 
  these_non_sires <- distance_df %>% 
    left_join(w, by = 'mother')
   
  # Add a new column to give two locus genotypes
  these_sires$two_locus <- paste(these_sires$rosea, these_sires$sulfurea, sep = "_")
  these_non_sires$two_locus <- paste(these_non_sires$rosea, these_non_sires$sulfurea, sep = "_")
  
  # Count the number of observed and simulated mating events in each spatial bin
  me <- cumulative_mating_events(
    these_sires,
    these_non_sires,
    bins = 'bins',
    phenotype = 'two_locus',
    weights = 'prob'
  )
  me$iter <- i
  
  # send the output to mating_events_all_mothers
  # The +1 is to account for Python counting from 0, not 1.
  mating_events_all_mothers[[i + 1]] <- me
}
close(pb) # Close the connection

# Glue the list together
mating_events_all_mothers <- do.call('rbind', mating_events_all_mothers)

write_csv(
  mating_events_all_mothers,
  "005.results/14_mating_by_distance/mating_by_distance_all_mothers.csv"
)
```

```{r plot-mating-events-all-mothers}

mating_events_all_mothers <- read_csv(
  "005.results/14_mating_by_distance/mating_by_distance_all_mothers.csv",
  col_types = 'fffddd'
)

mating_events_all_mothers %>% 
  filter(
    phenotype != "NaN_NaN"
  ) %>% 
  group_by(type, bins, phenotype) %>% 
  summarise(
    lower = quantile(n_sires, 0.02),
    upper = quantile(n_sires, 0.98),
    .groups = 'drop'
  ) %>% 
  pivot_longer(lower:upper) %>% 
  ggplot( aes(x= bins, y = value, colour = type, group = paste0(name,type)) ) +
  geom_line() +
  scale_x_discrete(labels=paste0("<",bins[-1])) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "Distance to father",
    y = "Cumulative mating events"
  ) +
  facet_grid( ~phenotype)

```


```{r calculate-mating-by-maternal-phenotype, eval=F}
#' Calculate observed and expected mating events in each deme separately for 
#' parental hybrid mothers.
#' Notice that this is flagged as `eval=FALSE` so that this does not need to be
# done every you knit this document; the next chunk imports the output from disk 

set.seed(18)

# A super list to hold mating events for each phenotype class
mating_by_mother <- vector('list', 3)
names(mating_by_mother) <- c("FR", "hybrid", "Ye")

for(colour in c("FR", "hybrid", "Ye")){
  # A vector of names of mothers of the current phenotype
  subset_names_by_colour <- py$am_data$flower_colours %>% 
    filter (simple_colour == colour) %>% 
    row.names()
  # Keep only those entries in distance_df for which the mother is the right colour
  these_plants <- distance_df %>% 
    filter(mother %in% subset_names_by_colour)
  
  iter <- unique(sires$iter) # vector of iteration labels (from a table created in Python)
  these_mating_events <- vector('list', length(iter)) # list to hold mating events for each iteration
  
  # Initializes the progress bar
  pb <- txtProgressBar(min = 0, max = max(iter), style = 3) 
  for(i in iter){
    setTxtProgressBar(pb, i)
    
    # Mating events on the subset of mothers, for one iteration only.
    these_sires <- sires %>%
      filter(
        iter == i,
        mother %in% subset_names_by_colour
      )
    
    # Add a weight to the data frame of distances to all males reflecting how many
    # mating events came from each mother.
    w <- these_sires %>% 
      group_by(mother) %>% 
      summarise(
        prob = sum(prob)
      ) %>% 
      mutate(
        prob = prob / max(prob)
      ) 
    these_non_sires <- distance_df %>% 
      left_join(w, by = 'mother')
    
    # A vector of two-locus Ros/Sulf genotypes
    these_sires$two_locus <- paste(these_sires$rosea, these_sires$sulfurea, sep = "_")
    these_non_sires$two_locus <- paste(these_non_sires$rosea, these_non_sires$sulfurea, sep = "_")
    
    # Calculate mating events in each deme
    me <- cumulative_mating_events(
      these_sires,# %>% filter(mother %in% this_colour),
      these_non_sires,# %>% filter(mother %in% this_colour),
      bins = 'bins',
      phenotype = 'two_locus',
      weights = 'prob'
    )
    me$iter <- i
    
    # send the output to these_mating_events.
    # The +1 is to account for Python counting from 0, not 1.
    these_mating_events[[i + 1]] <- me
  }
  close(pb) # Close the connection
  
  # Glue the list together
  these_mating_events <- do.call('rbind', these_mating_events)
  these_mating_events$maternal_phenotype <- colour
  
  mating_by_mother[[colour]] <- these_mating_events
}

mating_by_mother <- do.call('rbind', mating_by_mother)

write_csv(mating_by_mother, "005.results/14_mating_by_distance/mating_by_distance_by_maternal_phenotype.csv")

```

```{r plot-mating-by-maternal-phenotype}
mating_by_mother <- read_csv(
  "005.results/14_mating_by_distance/mating_by_distance_by_maternal_phenotype.csv",
  col_types = 'fffdddf'
  )


mating_by_mother %>% 
  filter(
    phenotype != "NaN_NaN"
  ) %>% 
  group_by(type, bins, maternal_phenotype, phenotype) %>% 
  summarise(
    lower = quantile(cumsum, 0.02),
    upper = quantile(cumsum, 0.98),
    .groups = 'drop'
  ) %>% 
  pivot_longer(lower:upper) %>% 
  ggplot( aes(x= bins, y = value, colour = type, group = paste0(name,type)) ) +
  geom_line() +
  labs(
    x = "Distance (m)",
    y = "Cumulative number of mating events"
  ) +
  scale_x_discrete(labels=paste0("<",bins[-1])) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(maternal_phenotype ~ phenotype)
```

```{r}
# This plots the same as the previous plot, but on a standard scale, rather than the cumulative scale.
# The assortment for yellow mothers goes away
mating_by_mother %>% 
  filter(
    phenotype != "NaN_NaN"
  ) %>% 
  group_by(type, bins, maternal_phenotype, phenotype) %>% 
  summarise(
    lower = quantile(n_sires, 0.02),
    upper = quantile(n_sires, 0.98),
    .groups = 'drop'
  ) %>% 
  pivot_longer(lower:upper) %>% 
  ggplot( aes(x= bins, y = value, colour = type, group = paste0(name,type)) ) +
  geom_line() +
  labs(
    x = "Distance (m)",
    y = "Cumulative number of mating events"
  ) +
  scale_x_discrete(labels=paste0("<",bins[-1])) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(maternal_phenotype ~ phenotype)
```



